-- V1__init_schema.sql

-- Department Table
CREATE TABLE department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- Users Table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    full_name VARCHAR(255),
    email VARCHAR(255),
    phone_number VARCHAR(20),
    matric_number VARCHAR(50),
    age INTEGER,
    level VARCHAR(50),
    profile_pic VARCHAR(255),
    admin_code VARCHAR(50),
    department_id BIGINT,
    CONSTRAINT fk_user_department FOREIGN KEY (department_id) REFERENCES department(id)
);

-- Course Table
CREATE TABLE course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    course_code VARCHAR(50),
    credit_units INTEGER,
    department_id BIGINT NOT NULL,
    lecturer_id BIGINT,
    CONSTRAINT fk_course_department FOREIGN KEY (department_id) REFERENCES department(id),
    CONSTRAINT fk_course_lecturer FOREIGN KEY (lecturer_id) REFERENCES users(id)
);

-- Assignment Table
CREATE TABLE assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    due_date TIMESTAMP,
    level VARCHAR(50),
    status VARCHAR(20) DEFAULT 'PUBLISHED' NOT NULL,
    created_by_id BIGINT,
    department_id BIGINT,
    course_id BIGINT,
    CONSTRAINT fk_assignment_creator FOREIGN KEY (created_by_id) REFERENCES users(id),
    CONSTRAINT fk_assignment_department FOREIGN KEY (department_id) REFERENCES department(id),
    CONSTRAINT fk_assignment_course FOREIGN KEY (course_id) REFERENCES course(id)
);

-- Forum Post Table
CREATE TABLE forum_post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT,
    timestamp TIMESTAMP,
    user_id BIGINT,
    course_id BIGINT,
    CONSTRAINT fk_post_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_post_course FOREIGN KEY (course_id) REFERENCES course(id)
);

-- Submission Table (Inferred structure)
CREATE TABLE submission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade INTEGER,
    feedback TEXT,
    submission_content VARCHAR(255),
    submitted_at TIMESTAMP,
    assignment_id BIGINT,
    student_id BIGINT,
    CONSTRAINT fk_submission_assignment FOREIGN KEY (assignment_id) REFERENCES assignment(id),
    CONSTRAINT fk_submission_student FOREIGN KEY (student_id) REFERENCES users(id)
);

-- Note: ClassSchedule table will be auto-generated by Hibernate if missing due to ddl-auto=update