-- V3__add_assignment_status.sql
-- Status column is now included in V1 migration
-- This migration is kept for backwards compatibility but does nothing
-- SELECT 'Status column already exists in assignment table' AS message;