-- V6__create_notification_table.sql
CREATE TABLE IF NOT EXISTS notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    message VARCHAR(1000),
    is_read BOOLEAN DEFAULT FALSE,
    timestamp TIMESTAMP,
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES users(id)
);