-- V7__create_course_material_table.sql
CREATE TABLE IF NOT EXISTS course_material (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    file_path VARCHAR(500),
    original_file_name VARCHAR(255),
    upload_date TIMESTAMP,
    course_id BIGINT,
    CONSTRAINT fk_course_material_course FOREIGN KEY (course_id) REFERENCES course(id)
);