-- V8__create_audit_log_table.sql
CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(255),
    entity_name VARCHAR(255),
    entity_id BIGINT,
    changed_by VARCHAR(255),
    details TEXT,
    timestamp TIMESTAMP
);