-- V9__create_class_schedule_table.sql
CREATE TABLE IF NOT EXISTS class_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT,
    day_of_week VARCHAR(20),
    start_time TIME,
    end_time TIME,
    room VARCHAR(100),
    CONSTRAINT fk_class_schedule_course FOREIGN KEY (course_id) REFERENCES course(id)
);